# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python Tests

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]

    steps:
    - uses: actions/checkout@v6
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Display Python version
      run: python -c "import sys; print(sys.version)"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[tests]
        sudo apt update
        sudo apt install podman screen
        pip install podman-compose
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Unit tests with pytest
      run: |
        pytest -k "not integration"
    - name: Prepare integration tests
      run: |
        mkdir -p tests/secrets
        ssh-keygen -t rsa -N '' -f tests/secrets/id_rsa_tests
        mkdir -p ~/.ssh
        touch ~/.ssh/config
        echo "Host docker-test" >> ~/.ssh/config
        echo "  Hostname localhost" >> ~/.ssh/config
        echo "  Port 2222" >> ~/.ssh/config
        echo "  IdentityFile tests/secrets/id_rsa_tests" >> ~/.ssh/config
        echo "  StrictHostKeyChecking no" >> ~/.ssh/config
        echo "" >> ~/.ssh/config
    - name: Integration tests with pytest and docker-compose
      run: |
        pytest -k "integration"
    - name: Run github.yaml with Automagix
      run: |
        screen -d -m -L -Logfile automagix_github.log automagix tests/github.yaml
        sleep 5
    - name: Check Automagix output
      run: |
        cat automagix_github.log
        grep 'github Test Automagix Script' automagix_github.log
        grep '(0) \[local\]: echo "The system is nonexistent.com"' automagix_github.log
        grep 'Test123nonexistent.comFalse' automagix_github.log
        grep 'Skip command, because the condition is not met.' automagix_github.log
